spring.application.name=fotoHub
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=aventura01
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.security.user.password=c3ed44c4-5019-4912-8da4-1d9650ecbedc

spring.jpa.hibernate.ddl-foto=update

spring.jwt.secret=ciaosonoandrea199919999ASDasdaSD
spring.jwt.expirationMs=1000000


cloudinary.cloud_name=dwutj7zy6
cloudinary.api_key=844187742654583
cloudinary.api_secret=SP8rl-zXeXrQISXbmymV1fAnFSU

# JavaMail Properties
gmail.mail.transport.protocol=smtp
gmail.mail.smtp.auth=true
gmail.mail.smtp.starttls.enable=true
gmail.mail.debug=true
gmail.mail.from=andrea.ventura23993@gmail.com
gmail.mail.from.password="besa ntqh abph mxgo"

# SMTP Properties
gmail.smtp.ssl.enable=true
gmail.smtp.host=smtp.gmail.com
gmail.smtp.port=587